spring:
  application:
    name: main_server

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

    mongodb:
      uri: ${MONGO_DB_URL}

graph:
  api:
    tenant-id: ${GRAPH_API_TENANT_ID}
    client-id: ${GRAPH_API_CLIENT_ID}
    client-secret: ${GRAPH_API_CLIENT_SECRET}
    scope: ${GRAPH_API_SCOPE}

server:
  port: ${PORT}
  ai:
    url: ${AI_SERVER_URL}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 1296000000
  refresh-expiration: 2596000000