apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-team-05-back-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-team-05-back
  template:
    metadata:
      labels:
        app: sk-team-05-back
    spec:
      containers:
        - name: sk-team-05-back
          image: idealhyun2/leadme5-back:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-mariadb-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-mariadb-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-mariadb-secret
                  key: DB_PASSWORD