apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-team-05-back-deployment
  namespace: sk-team-05
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-team-05-back
  template:
    metadata:
      labels:
        app: sk-team-05-back
    spec:
      containers:
        - name: sk-team-05-back
          image: idealhyun2/leadme5-back:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: DB_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: REDIS_URL
            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: REDIS_PORT
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: MONGO_DB_URL
            - name: GRAPH_API_TENANT_ID
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: GRAPH_API_TENANT_ID
            - name: GRAPH_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: GRAPH_API_CLIENT_ID
            - name: GRAPH_API_SCOPE
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: GRAPH_API_SCOPE
            - name: GRAPH_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: GRAPH_API_CLIENT_SECRET
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: sk-team-05-back-secret
                  key: PORT
